# Build file injected into the `vunit_hdl` http_archive by `MODULE.bazel`.

load("@rules_venv//python:py_library.bzl", "py_library")

py_library(
    name = "vunit_hdl",
    srcs = glob(["vunit/**/*.py"]),
    data = [
    ] + glob(
        include = [
            "vunit/**/py.typed",
            "vunit/**/*.cmd",
            "vunit/**/*.filter",
            "vunit/**/*.gtkw",
            "vunit/**/*.json",
            "vunit/**/*.ldf",
            "vunit/**/*.log",
            "vunit/**/*.lpf",
            "vunit/**/*.md",
            "vunit/**/*.pro",
            "vunit/**/*.ps1",
            "vunit/**/*.sh",
            "vunit/**/*.sty",
            "vunit/**/*.sv",
            "vunit/**/*.svh",
            "vunit/**/*.tcl",
            "vunit/**/*.vhd",
            "vunit/**/*.vhdl",
            "vunit/**/*.xise",
            "vunit/**/*.xpr",
            "vunit/**/*.yml",
        ],
        allow_empty = True,
    ),
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        # Consumers should pair this target with `colorama` but it is not
        # added here to avoid introducing conflicts in existing dep trees
    ],
)
